fix(comp): empty data warning should work with autoheight grid, fix #671
ghiscoding/Angular-Slickgrid pull request #672
Opened 2021-01-12 19:30 UTC by ghiscoding

2021-01-13 01:05 UTC, denhaandrei requested changes
Thanks for your quick response.
I`m apply your changes on my
[slick-empty-warning.component.txt](https://github.com/ghiscoding/Angular-Slickgrid/files/5805748/slick-empty-warning.component.txt)
[angular-slickgrid.component.txt](https://github.com/ghiscoding/Angular-Slickgrid/files/5805749/angular-slickgrid.component.txt)

 environment and this is not work. 
1. I`m add some fixes and test it. It`s work for me(one row, multy row, huge grid).
how to fix (use minHeight when use height - render is not always call)
also remove min-height settings when message is not showing
2. Also, i`m add refresh warning after grid showing on form because this.grid in warning component return undefined

Please, review files and include this changes.

2021-01-13 01:31 UTC, ghiscoding commented
sorry but your English is really hard to read, it works properly for me, if you have other code suggestion then put it in here or in the PR. I won't download/open any external files for security reasons.

2021-01-13 01:43 UTC, denhaandrei commented
Sorry, write from mobile...
Open for you:
Warning component:

import { Optional } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import * as DOMPurify from 'dompurify';
import { EmptyWarning, GridOption } from '../models/index';

export class SlickEmptyWarningComponent {
    private _grid: any;
    private _warningLeftElement: HTMLDivElement | null;
    private _warningRightElement: HTMLDivElement | null;

    /** Getter for the Grid Options pulled through the Grid Object */
    get gridOptions(): GridOption {
        return (this._grid && this._grid.getOptions) ? this._grid.getOptions() : {};
    }

    set grid(slickGrid: any) {
        this._grid = slickGrid;
    }

    constructor(@Optional() private translate?: TranslateService) { }

    dispose() {
        if (this._warningLeftElement && this._warningLeftElement.remove) {
            this._warningLeftElement.remove();
        }
        if (this._warningRightElement && this._warningRightElement.remove) {
            this._warningRightElement.remove();
        }
        this._warningLeftElement = null;
        this._warningRightElement = null;
    }

    /**
     * Display a warning of empty data when the filtered dataset is empty
     * NOTE: to make this code reusable, you could (should) move this code into a utility service
     * @param isShowing - are we showing the message?
     * @param options - any styling options you'd like to pass like the text color
     */

    private isPreviousShowing: boolean = false;//remove multyRefresh
    private defHeightPane: number = null;
    private defHeightRow: number = null;
    private defMinHeightPane: string = null;
    private defMinHeightRow: string = null;

    showEmptyDataMessage(isShowing = true, options?: EmptyWarning): boolean {
        if (!this._grid || !this.gridOptions || this.isPreviousShowing == isShowing) {
            return false;
        }
        
        this.isPreviousShowing = isShowing;

        const gridUid = this._grid && this._grid.getUID();
        const defaultMessage = 'No data to display.';
        const mergedOptions: EmptyWarning = { message: defaultMessage, ...this.gridOptions.emptyDataWarning, ...options };
        const emptyDataClassName = mergedOptions && mergedOptions.className || 'slick-empty-data-warning';
        this._warningLeftElement = document.querySelector<HTMLDivElement>(`.${gridUid} .${emptyDataClassName}`);
        const leftPaneElm = document.querySelector<HTMLDivElement>('.slick-pane.slick-pane-top.slick-pane-left');
        const gridCanvasLeftElm = document.querySelector<HTMLDivElement>(`.${gridUid} .grid-canvas.grid-canvas-left`);
        const gridCanvasRightElm = document.querySelector<HTMLDivElement>(`.${gridUid} .grid-canvas.grid-canvas-right`);
        const leftElementMarginLeft = mergedOptions.leftViewportMarginLeft || 0;
        const rightElementMarginLeft = mergedOptions.rightViewportMarginLeft || 0;
        const leftElementFrozenMarginLeft = mergedOptions.frozenLeftViewportMarginLeft || 0;
        const rightElementFrozenMarginLeft = mergedOptions.frozenRightViewportMarginLeft || 0;
        const isFrozenGrid = (this.gridOptions.frozenColumn !== undefined && this.gridOptions.frozenColumn >= 0);
        const leftViewportMarginLeft = typeof leftElementMarginLeft === 'string' ? leftElementMarginLeft : `${leftElementMarginLeft}px`;
        const rightViewportMarginLeft = typeof rightElementMarginLeft === 'string' ? rightElementMarginLeft : `${rightElementMarginLeft}px`;

        //GetDefaultValues
        if (this.defMinHeightPane == null || this.defMinHeightRow == null || this.defHeightRow == null) {
            this.defMinHeightPane = leftPaneElm.style.minHeight;
            this.defMinHeightRow = gridCanvasLeftElm.style.minHeight;
            this.defHeightPane = parseInt(leftPaneElm.style.height, 10);//this field auto calc by row height
            this.defHeightRow = this.gridOptions.rowHeight;
        }

        if (!this._warningLeftElement && !isShowing) {
            return false;
        }

        // when dealing with a grid that has "autoHeight" option, we need to override 2 height that get miscalculated
        // that is because it is not aware that we are adding this slick empty element in this grid DOM
        if (this.gridOptions.autoHeight) {
            if (leftPaneElm && leftPaneElm.style && gridCanvasLeftElm && gridCanvasLeftElm.style) {
                if (isShowing) {
                    //Use when height with rows more that 100px 
                    //AutoHeight option collapse dataview to 100px when show message without data in huge grid
                    //(default autoHeight for message - 100px you can add as param if need)
                    if (this.defHeightPane != null && this.defHeightPane < 100)
                        leftPaneElm.style.minHeight = `${this.defHeightPane}px`;
                    else
                        leftPaneElm.style.minHeight = '100px';
                    gridCanvasLeftElm.style.minHeight = `${this.defHeightRow}px`;
                }
                //restore settings to default
                else if (this.defMinHeightPane != null && this.defMinHeightRow != null && this.defHeightRow != null) {
                    leftPaneElm.style.minHeight = this.defMinHeightPane;
                    gridCanvasLeftElm.style.minHeight = this.defMinHeightRow;
                    gridCanvasLeftElm.style.height = `${this.defHeightRow}px`
                    this.defMinHeightPane = null
                    this.defMinHeightRow = null
                    this.defHeightRow = null
                }
            }
        }

        // warning message could come from a translation key or by the warning options
        let warningMessage = mergedOptions.message;
        if (this.gridOptions.enableTranslate && this.translate && this.translate.instant && mergedOptions && mergedOptions.messageKey) {
            warningMessage = this.translate.instant(mergedOptions.messageKey);
        }

        if (!this._warningLeftElement && gridCanvasLeftElm && gridCanvasRightElm) {
            const sanitizedOptions = this.gridOptions && this.gridOptions.sanitizeHtmlOptions || {};

            // sanitize any unauthorized html tags like script and others
            // for the remaining allowed tags we'll permit all attributes
            const sanitizedText = (DOMPurify.sanitize(warningMessage, sanitizedOptions) || '').toString();

            this._warningLeftElement = document.createElement('div');
            this._warningLeftElement.classList.add(emptyDataClassName);
            this._warningLeftElement.classList.add('left');
            this._warningLeftElement.innerHTML = sanitizedText;

            // clone the warning element and add the "right" class to it so we can distinguish
            this._warningRightElement = this._warningLeftElement.cloneNode(true) as HTMLDivElement;
            this._warningRightElement.classList.add('right');

            // append both warning elements to both left/right canvas
            gridCanvasRightElm.appendChild(this._warningRightElement);
            gridCanvasLeftElm.appendChild(this._warningLeftElement);
        }

        // if we did find the Slick-Empty-Warning element then we'll display/hide at the grid position with some margin offsets (we need to position under the headerRow and filterRow)
        // when using a frozen/pinned grid, we also have extra options to hide left/right message
        if (this._warningLeftElement) {
            // display/hide right/left messages
            let leftDisplay = isShowing ? 'block' : 'none';
            if (isFrozenGrid && isShowing) {
                leftDisplay = (mergedOptions.hideFrozenLeftWarning) ? 'none' : 'block';
            }
            this._warningLeftElement.style.display = leftDisplay;

            // use correct left margin (defaults to 40% on regular grid or 10px on frozen grid)
            const leftFrozenMarginLeft =  [...]

2021-01-13 01:48 UTC, ghiscoding commented
sorry again but I can't go in 1000 lines of code to see what you changed... please provide only the code to change and maybe or even better write it with ` ```diff ` and add `+` or `-` in front of the line to change. For example 

```diff
- alert('text'`);
+ alert('something');
```

2021-01-13 01:50 UTC, denhaandrei commented
showEmptyDataMessage(isShowing = true, options?: EmptyWarning): boolean {
        if (!this._grid || !this.gridOptions || this.isPreviousShowing == isShowing) {
            return false;
        }
        
        this.isPreviousShowing = isShowing;

        const gridUid = this._grid && this._grid.getUID();
        const defaultMessage = 'No data to display.';
        const mergedOptions: EmptyWarning = { message: defaultMessage, ...this.gridOptions.emptyDataWarning, ...options };
        const emptyDataClassName = mergedOptions && mergedOptions.className || 'slick-empty-data-warning';
        this._warningLeftElement = document.querySelector<HTMLDivElement>(`.${gridUid} .${emptyDataClassName}`);
        const leftPaneElm = document.querySelector<HTMLDivElement>('.slick-pane.slick-pane-top.slick-pane-left');
        const gridCanvasLeftElm = document.querySelector<HTMLDivElement>(`.${gridUid} .grid-canvas.grid-canvas-left`);
        const gridCanvasRightElm = document.querySelector<HTMLDivElement>(`.${gridUid} .grid-canvas.grid-canvas-right`);
        const leftElementMarginLeft = mergedOptions.leftViewportMarginLeft || 0;
        const rightElementMarginLeft = mergedOptions.rightViewportMarginLeft || 0;
        const leftElementFrozenMarginLeft = mergedOptions.frozenLeftViewportMarginLeft || 0;
        const rightElementFrozenMarginLeft = mergedOptions.frozenRightViewportMarginLeft || 0;
        const isFrozenGrid = (this.gridOptions.frozenColumn !== undefined && this.gridOptions.frozenColumn >= 0);
        const leftViewportMarginLeft = typeof leftElementMarginLeft === 'string' ? leftElementMarginLeft : `${leftElementMarginLeft}px`;
        const rightViewportMarginLeft = typeof rightElementMarginLeft === 'string' ? rightElementMarginLeft : `${rightElementMarginLeft}px`;

        //GetDefaultValues
        if (this.defMinHeightPane == null || this.defMinHeightRow == null || this.defHeightRow == null) {
            this.defMinHeightPane = leftPaneElm.style.minHeight;
            this.defMinHeightRow = gridCanvasLeftElm.style.minHeight;
            this.defHeightPane = parseInt(leftPaneElm.style.height, 10);//this field auto calc by row height
            this.defHeightRow = this.gridOptions.rowHeight;
        }

        if (!this._warningLeftElement && !isShowing) {
            return false;
        }

        // when dealing with a grid that has "autoHeight" option, we need to override 2 height that get miscalculated
        // that is because it is not aware that we are adding this slick empty element in this grid DOM
        if (this.gridOptions.autoHeight) {
            if (leftPaneElm && leftPaneElm.style && gridCanvasLeftElm && gridCanvasLeftElm.style) {
                if (isShowing) {
                    //Use when height with rows more that 100px 
                    //AutoHeight option collapse dataview to 100px when show message without data in huge grid
                    //(default autoHeight for message - 100px you can add as param if need)
                    if (this.defHeightPane != null && this.defHeightPane < 100)
                        leftPaneElm.style.minHeight = `${this.defHeightPane}px`;
                    else
                        leftPaneElm.style.minHeight = '100px';
                    gridCanvasLeftElm.style.minHeight = `${this.defHeightRow}px`;
                }
                //restore settings to default
                else if (this.defMinHeightPane != null && this.defMinHeightRow != null && this.defHeightRow != null) {
                    leftPaneElm.style.minHeight = this.defMinHeightPane;
                    gridCanvasLeftElm.style.minHeight = this.defMinHeightRow;
                    gridCanvasLeftElm.style.height = `${this.defHeightRow}px`
                    this.defMinHeightPane = null
                    this.defMinHeightRow = null
                    this.defHeightRow = null
                }
            }
        }

        // warning message could come from a translation key or by the warning options
        let warningMessage = mergedOptions.message;
        if (this.gridOptions.enableTranslate && this.translate && this.translate.instant && mergedOptions && mergedOptions.messageKey) {
            warningMessage = this.translate.instant(mergedOptions.messageKey);
        }

        if (!this._warningLeftElement && gridCanvasLeftElm && gridCanvasRightElm) {
            const sanitizedOptions = this.gridOptions && this.gridOptions.sanitizeHtmlOptions || {};

            // sanitize any unauthorized html tags like script and others
            // for the remaining allowed tags we'll permit all attributes
            const sanitizedText = (DOMPurify.sanitize(warningMessage, sanitizedOptions) || '').toString();

            this._warningLeftElement = document.createElement('div');
            this._warningLeftElement.classList.add(emptyDataClassName);
            this._warningLeftElement.classList.add('left');
            this._warningLeftElement.innerHTML = sanitizedText;

            // clone the warning element and add the "right" class to it so we can distinguish
            this._warningRightElement = this._warningLeftElement.cloneNode(true) as HTMLDivElement;
            this._warningRightElement.classList.add('right');

            // append both warning elements to both left/right canvas
            gridCanvasRightElm.appendChild(this._warningRightElement);
            gridCanvasLeftElm.appendChild(this._warningLeftElement);
        }

        // if we did find the Slick-Empty-Warning element then we'll display/hide at the grid position with some margin offsets (we need to position under the headerRow and filterRow)
        // when using a frozen/pinned grid, we also have extra options to hide left/right message
        if (this._warningLeftElement) {
            // display/hide right/left messages
            let leftDisplay = isShowing ? 'block' : 'none';
            if (isFrozenGrid && isShowing) {
                leftDisplay = (mergedOptions.hideFrozenLeftWarning) ? 'none' : 'block';
            }
            this._warningLeftElement.style.display = leftDisplay;

            // use correct left margin (defaults to 40% on regular grid or 10px on frozen grid)
            const leftFrozenMarginLeft = typeof leftElementFrozenMarginLeft === 'string' ? leftElementFrozenMarginLeft : `${leftElementFrozenMarginLeft}px`;
            this._warningLeftElement.style.marginLeft = isFrozenGrid ? leftFrozenMarginLeft : leftViewportMarginLeft;
        }

        if (this._warningRightElement) {
            // use correct left margin (defaults to 40% on regular grid or 10px on frozen grid)
            let rightDisplay = isShowing ? 'block' : 'none';
            if (isFrozenGrid && isShowing) {
                rightDisplay = (mergedOptions.hideFrozenRightWarning) ? 'none' : 'block';
            }
            this._warningRightElement.style.display = rightDisplay;

            // use correct left margin (defaults to 40% on regular grid or 10px on frozen grid)
            const rightFrozenMarginLeft = typeof rightElementFrozenMarginLeft === 'string' ? rightElementFrozenMarginLeft : `${rightElementFrozenMarginLeft}px`;
            this._warningRightElement.style.marginLeft = isFrozenGrid ? rightFrozenMarginLeft : rightViewportMarginLef;
        }

        return isShowing;
    }

2021-01-13 01:53 UTC, denhaandrei commented
In the angular-slickgrid.component.ts
Replace mhetod:

ngAfterViewInit() {
this.initialization();
this._isGridInitialized = true;

// user must provide a "gridHeight" or use "autoResize: true" in the grid options
if (!this._fixedHeight && !this.gridOptions.enableAutoResize) {
  throw new Error(
    `[Angular-Slickgrid] requires a "grid-height" or the "enableAutoResize" grid option to be enabled.
    Without that the grid will seem empty while in fact it just does not have any height define.`
  );
}
  //refresh message after grid shown because call in method refreshGridData not work when grid not shown on form(this.grid return undefined in method this.slickEmptyWarning.showEmptyDataMessage)
  if (this.gridOptions && this.gridOptions.enableEmptyDataWarningMessage && Array.isArray(this.dataset)) {
      const finalTotalCount = this.dataset.length;
      this.displayEmptyDataWarning(finalTotalCount < 1);
  }
}

2021-01-13 01:57 UTC, denhaandrei commented
I'm add 2 comments with 2 replaced method's.
1. ngAfterViewInit in the component angular-slickgrid
2. showEmptyDataMessage in the component slick-empty-warning
It's clear for you?

2021-01-13 14:42 UTC, denhaandrei commented
> sorry again but I can't go in 1000 lines of code to see what you changed... please provide only the code to change and maybe or even better write it with `` ```diff `` and add `+` or `-` in front of the line to change. For example
> 
> ```diff
> - alert('text'`);
> + alert('something');
> ```

Updated

2021-01-13 15:31 UTC, ghiscoding commented
Thanks it is easier to read now, I don't have time to review it all now, will do later. That is a lot of code change and I don't know how to tests everything and that will lower my unit tests coverage. Do you have all the steps to test all your new code? (when this do that, ...)

2021-01-14 11:00 UTC, denhaandrei commented
> Thanks it is easier to read now, I don't have time to review it all now, will do later. That is a lot of code change and I don't know how to tests everything and that will lower my unit tests coverage. Do you have all the steps to test all your new code? (when this do that, ...)

Hi, I have no unit tests for this code. Try calling filtering a few times to test this with isShowing (true, false, true). But it works well on UI tests for my project.

2021-01-14 12:58 UTC, ghiscoding commented
The question is, why did you added so much code? The code I added in the original PR is working for me, so what does your code add? I need to know what your code fixes so I can add unit tests for them

2021-01-14 13:50 UTC, denhaandrei commented
> The question is, why did you added so much code? The code I added in the original PR is working for me, so what does your code add? I need to know what your code fixes so I can add unit tests for them

Hi,

1. angular-slickgrid.component.ts -> ngAfterViewInit changed. 
When you use this grid on modal form and load data before shown grid stack trace is next:
 constructor -> refresh data -> this.slickEmptyWarning.showEmptyDataMessage() but property this.grid return undefined(because modal is not shown) and showEmptyDataMessage go out by this code and don`t refresh message:
```
if (!this._grid || !this.gridOptions || this.isPreviousShowing == isShowing) {
           return false;
       }
```
So, after shown you need call showEmptyDataMessage() again to refresh this message 

2. slick-empty-warning.component.ts -> showEmptyDataMessage changed.
2.1. Add variable: this.isPreviousShowing  - do not call any logic when current state of control not changed
2.2. Work with min-height(not use height) - when grid render the some height calculated by height value!!!!
Your code:
```
       const leftPaneHeight = parseInt(leftPaneElm.style.height, 10) || 0;
       const gridRowHeight = this.gridOptions.rowHeight || 0;
       leftPaneElm.style.height = `${leftPaneHeight + gridRowHeight}px`;
       gridCanvasLeftElm.style.height = `${gridRowHeight}px`;
```
Problem, with:
 ``` leftPaneElm.style.height = `${leftPaneHeight + gridRowHeight}px`;```
Can be calculated multiple times calling example:
Input value: leftPaneElm.style.height = 30px, this.gridOptions.rowHeight = 10px;
- First call return:
```
const leftPaneHeight = 30px;
const gridRowHeight =10px;
leftPaneElm.style.height = 30+10 = 40px;
gridCanvasLeftElm.style.height = 10px;
 ```
- Second call return:
```
const leftPaneHeight = 40px;
const gridRowHeight =10px;
leftPaneElm.style.height = 40+10 = 50px;
gridCanvasLeftElm.style.height = 10px;
 ```
- Third call return:
```
const leftPaneHeight = 50px;
const gridRowHeight =10px;
leftPaneElm.style.height = 50+10 = 60px;
gridCanvasLeftElm.style.height = 10px;
 ```
More flexible to use min-height.
But you need remember this to restore this values when do not show the warning message.
So i`m add next variables to restore this values:
 ```
this.defMinHeightPane;
this.defMinHeightRow;
this.defHeightRow
 ```
3. defHeightPane field for calculate when need change size to huge grid(20+rows) to remove scroll in empty grid.
This field is no need to restore because it`s auto recalculate when rows count changed.

Thanks,
Andrey

2021-01-18 22:36 UTC, ghiscoding commented
I tried your code and it works when the grid has no data but it was not working when there is data and we then filter something that doesn't exist (like `zzz`), the warning is supposed to show but was not showing with your code. So there is a reason why I was doing the calculation of `leftPaneHeight + gridRowHeight` and that is because the height must include at least these elements when enabled
- item row height (always)
- header column title header row (defined in CSS)
- filter row height (when `enableFiltering` is enabled, then use `headerRowHeight`)
- preHeader panel row height (when `createPreHeaderPanel` is enabled, then use `preHeaderPanelHeight`)

At the end both my code and your code were wrong.

Also note that the reason why I use the `height` is because SlickGrid will always calculate the row height, you will see that each row has a height in its style, now you provide a `minHeight` but the row still has something like this `<div style="height: 0px"></div>` because SlickGrid always calculates it and always uses the `style` to re-apply it on each row but also on the grid pane div and because of that I see your `minHeight` + `height: 0px`, not exactly great. 

I am adding the code in the PR you can try, 
Note that I did not add the restoring of `= null` because I don't think that is really necessary and even after trying couple of ways to unit test it, I could never fall in that section. So if you really need it, then please tell me how to properly test it. I tried with the following and it does not go in that section 
```ts
      component.showEmptyDataMessage(true);
      component.showEmptyDataMessage(false);
      component.showEmptyDataMessage(true);
```

2021-01-18 23:39 UTC, denhaandrei commented
> In the slick-empty-warning.component.ts replace method showEmptyDataMessage:
> 
> ```diff
> +   private isPreviousShowing: boolean = false;//remove multyRefresh
> +   private defHeightPane: number = null;
> +   private defHeightRow: number = null;
> +   private defMinHeightPane: string = null;
> +   private defMinHeightRow: string = null;
> 
>      showEmptyDataMessage(isShowing = true, options?: EmptyWarning): boolean {
> -		if (!this._grid || !this.gridOptions) {
> +       if (!this._grid || !this.gridOptions || this.isPreviousShowing == isShowing) {
>            return false;
>        }
>        
> +       this.isPreviousShowing = isShowing;
> 
>        const gridUid = this._grid && this._grid.getUID();
>        const defaultMessage = 'No data to display.';
>        const mergedOptions: EmptyWarning = { message: defaultMessage, ...this.gridOptions.emptyDataWarning, ...options };
>        const emptyDataClassName = mergedOptions && mergedOptions.className || 'slick-empty-data-warning';
>        this._warningLeftElement = document.querySelector<HTMLDivElement>(`.${gridUid} .${emptyDataClassName}`);
>        const gridCanvasLeftElm = document.querySelector<HTMLDivElement>(`.${gridUid} .grid-canvas.grid-canvas-left`);
>        const gridCanvasRightElm = document.querySelector<HTMLDivElement>(`.${gridUid} .grid-canvas.grid-canvas-right`);
>        const leftElementMarginLeft = mergedOptions.leftViewportMarginLeft || 0;
>        const rightElementMarginLeft = mergedOptions.rightViewportMarginLeft || 0;
>        const leftElementFrozenMarginLeft = mergedOptions.frozenLeftViewportMarginLeft || 0;
>        const rightElementFrozenMarginLeft = mergedOptions.frozenRightViewportMarginLeft || 0;
>        const isFrozenGrid = (this.gridOptions.frozenColumn !== undefined && this.gridOptions.frozenColumn >= 0);
>        const leftViewportMarginLeft = typeof leftElementMarginLeft === 'string' ? leftElementMarginLeft : `${leftElementMarginLeft}px`;
>        const rightViewportMarginLeft = typeof rightElementMarginLeft === 'string' ? rightElementMarginLeft : `${rightElementMarginLeft}px`;
> 
>        if (!this._warningLeftElement && !isShowing) {
>            return false;
>        }
> 
>        // when dealing with a grid that has "autoHeight" option, we need to override 2 height that get miscalculated
>        // that is because it is not aware that we are adding this slick empty element in this grid DOM
>        if (this.gridOptions.autoHeight) {
> +       const leftPaneElm = document.querySelector<HTMLDivElement>('.slick-pane.slick-pane-top.slick-pane-left');
> +       //GetDefaultValues
> +       if (this.defMinHeightPane == null || this.defMinHeightRow == null || this.defHeightRow == null) {
> +           this.defMinHeightPane = leftPaneElm.style.minHeight;
> +           this.defMinHeightRow = gridCanvasLeftElm.style.minHeight;
> +           this.defHeightPane = parseInt(leftPaneElm.style.height, 10);//this field auto calc by row height
> +           this.defHeightRow = this.gridOptions.rowHeight;
> +       }
>            if (leftPaneElm && leftPaneElm.style && gridCanvasLeftElm && gridCanvasLeftElm.style) {
> -		    const leftPaneHeight = parseInt(leftPaneElm.style.height, 10) || 0;
> -			const gridRowHeight = this.gridOptions.rowHeight || 0;
> -			leftPaneElm.style.height = `${leftPaneHeight + gridRowHeight}px`;
> -			gridCanvasLeftElm.style.height = `${gridRowHeight}px`;
> +               if (isShowing) {
> +                   //Use when height with rows more that 100px 
> +                   //AutoHeight option collapse dataview to 100px when show message without data in huge grid
> +                   //(default autoHeight for message - 100px you can add as param if need)
> +                   if (this.defHeightPane != null && this.defHeightPane < 100)
> +                       leftPaneElm.style.minHeight = `${this.defHeightPane}px`;
> +                   else
> +                       leftPaneElm.style.minHeight = '100px';
> +                   gridCanvasLeftElm.style.minHeight = `${this.defHeightRow}px`;
> +               }
> +               //restore settings to default
> +               else if (this.defMinHeightPane != null && this.defMinHeightRow != null && this.defHeightRow != null) {
> +                   leftPaneElm.style.minHeight = this.defMinHeightPane;
> +                   gridCanvasLeftElm.style.minHeight = this.defMinHeightRow;
> +                   gridCanvasLeftElm.style.height = `${this.defHeightRow}px`
> +                   this.defMinHeightPane = null
> +                   this.defMinHeightRow = null
> +                   this.defHeightRow = null
> +               }
> +           }
> +       }
> 
>         // warning message could come from a translation key or by the warning options
>         let warningMessage = mergedOptions.message;
>         if (this.gridOptions.enableTranslate && this.translate && this.translate.instant && mergedOptions && mergedOptions.messageKey) {
>             warningMessage = this.translate.instant(mergedOptions.messageKey);
>         }
> 
>         if (!this._warningLeftElement && gridCanvasLeftElm && gridCanvasRightElm) {
>             const sanitizedOptions = this.gridOptions && this.gridOptions.sanitizeHtmlOptions || {};
> 
>             // sanitize any unauthorized html tags like script and others
>             // for the remaining allowed tags we'll permit all attributes
>             const sanitizedText = (DOMPurify.sanitize(warningMessage, sanitizedOptions) || '').toString();
> 
>             this._warningLeftElement = document.createElement('div');
>             this._warningLeftElement.classList.add(emptyDataClassName);
>             this._warningLeftElement.classList.add('left');
>             this._warningLeftElement.innerHTML = sanitizedText;
> 
>             // clone the warning element and add the "right" class to it so we can distinguish
>             this._warningRightElement = this._warningLeftElement.cloneNode(true) as HTMLDivElement;
>             this._warningRightElement.classList.add('right');
> 
>             // append both warning elements to both left/right canvas
>             gridCanvasRightElm.appendChild(this._warningRightElement);
>             gridCanvasLeftElm.appendChild(this._warningLeftElement);
>         }
> 
>         // if we did find the Slick-Empty-Warning element then we'll display/hide at the grid position with some margin offsets (we need to position under the headerRow and filterRow)
>         // when using a frozen/pinned grid, we also have extra options to hide left/right message
>         if (this._warningLeftElement) {
>             // display/hide right/left messages
>             let leftDisplay = isShowing ? 'block' : 'none';
>             if (isFrozenGrid && isShowing) {
>                 leftDisplay = (mergedOptions.hideFrozenLeftWarning) ? 'none' : 'block';
>             }
>             this._warningLeftElement.style.display = leftDisplay;
> 
>             // use correct left margin (defaults to 40% on regular grid or 10px on frozen grid)
>             const leftFrozenMarginLeft = typeof leftElementFrozenMarginLeft === 'string' ? leftElementFrozenMarginLeft : `${leftElementFrozenMarginLeft}px`;
>             this._warningLeftElement.style.marginLeft = isFrozenGrid ? leftFrozenMarginLeft : leftViewportMarginLeft;
>         }
> 
>         if (this._warningRightElement) {
>             // use correct left margin (defaults to 40% on regular grid or 10px on frozen grid)
>             let rightDisplay = isShowing ? 'block' : 'none';
>             if (isFrozenGrid && isShowing) {
>                 rightDisplay = (mergedOptions.hideFrozenRightWarning) ? 'none' : 'block';
>             }
>             this._warningRightElement.style.display = rightDisplay;
> 
>             // use correct left margin (defaults to 40% on regular grid or 10px on frozen grid)
>             const rightFrozenMarginLeft = typeof rightElementFrozenMarginLeft === 'string' ? rightElem [...]

2021-01-18 23:46 UTC, ghiscoding commented
I already did say that I tried your code but I had to modify it because it does not cover every use case...

> I tried your code and it works when the grid has no data but it was not working when there is data and we then filter something that doesn't exist (like "zzz"), the warning is supposed to show but was not showing with your code.

You should get my latest code and try it with that, all use cases I tried now works.

2021-01-18 23:51 UTC, denhaandrei commented
Ok, i try it tomorrow, but on paper for me its not work. 
minHeight must be restored.

Thanks, Andrey

2021-01-19 11:55 UTC, denhaandrei commented
Hi @ghiscoding ,

It works for me. But I'm worried that you are not resetting min-heights to their defaults.
I recomend the next changes:
1.1 Set default values one time(only when this values not set)
```diff
+ 74       if (this.defMinHeightPane == null || this.defMinHeightRow == null || this.defHeightRow == null)
+ 75       {
...             this.defMinHeightPane = leftPaneElm.style.minHeight;
                this.defMinHeightRow = gridCanvasLeftElm.style.minHeight;
                this.defHeightPane = parseInt(leftPaneElm.style.height, 10);

                 // get row height of each feature when enabled (rowHeight will always be defined because that is cell height)
                 this.defHeightRow = this.gridOptions.rowHeight;
+ 82        }
```
1.2. Restore settings. 
In the debug i can check next code and restore values to default. I don't understand why the tests can`t test this.
```
      component.showEmptyDataMessage(true);
      component.showEmptyDataMessage(false);
      component.showEmptyDataMessage(true);
```
```diff
+ 93               //restore settings to default
+ 94              else if (this.defMinHeightPane != null && this.defMinHeightRow != null && this.defHeightRow != null) {
+ 95                  leftPaneElm.style.minHeight = this.defMinHeightPane;
+ 96                  gridCanvasLeftElm.style.minHeight = this.defMinHeightRow;
+ 97                  gridCanvasLeftElm.style.height = `${this.defHeightRow}px`
+ 98                  this.defMinHeightPane = null
+ 99                  this.defMinHeightRow = null
+ 100                 this.defHeightRow = null
+ 101             }
```
2.1 Why didn't you make the change in the file angular-slickgrid.component.ts?(It fix next problem: After modal window shown 
 with empty grid "angular-slickgrid", empty grid message not showing)
```diff
261  ngAfterViewInit() {
262   this.initialization();
263    this._isGridInitialized = true;
264
265    // user must provide a "gridHeight" or use "autoResize: true" in the grid options
266    if (!this._fixedHeight && !this.gridOptions.enableAutoResize) {
267      throw new Error(
268        `[Angular-Slickgrid] requires a "grid-height" or the "enableAutoResize" grid option to be enabled.
269        Without that the grid will seem empty while in fact it just does not have any height define.`
270      );
271      }
+ 272      //refresh message after grid shown because call in method refreshGridData not work when grid not shown on form(this.grid return undefined in method refreshGridData)
+ 273     if (this.gridOptions && this.gridOptions.enableEmptyDataWarningMessage && Array.isArray(this.dataset)) {
+ 274        const finalTotalCount = this.dataset.length;
+ 275         this.displayEmptyDataWarning(finalTotalCount < 1);
+ 276     }
277    }
```
Thanks,
Andrey

2021-01-19 13:20 UTC, ghiscoding commented
I think you did not read all the comments I left for you... please read them [here](https://github.com/ghiscoding/Angular-Slickgrid/pull/672#issuecomment-762499059). I told you a few times already, if there is no way to test it then I won't code that I can't test. 

> 2.1 Why didn't you make the change in the file angular-slickgrid.component.ts?

I put the code in a different place, I don't want to add code in the `ngAfterViewInit` as much as possible. I tested that by passing an empty dataset to the autoHeight example. Doesn't it work for you?

2021-01-19 13:27 UTC, denhaandrei commented
> I put the code in a different place, I don't want to add code in the ngAfterViewInit as much as possible. I tested that by passing an empty dataset to the autoHeight example. Doesn't it work for you?

Hi, sorry
1.1 and 1.2 This is only my recommendations. I do not order to do this.
2.1. Now it doesn't work for me = (

2021-01-19 20:16 UTC, ghiscoding commented
ok I moved the code into the `ngAfterViewInit` like you had originally, if that works for you then I would like to close this PR and the subject

2021-01-19 21:30 UTC, denhaandrei commented
> ok I moved the code into the `ngAfterViewInit` like you had originally, if that works for you then I would like to close this PR and the subject

Ok, thanks are lot!

2021-01-19 21:33 UTC, ghiscoding commented
Have you tested it? Can I merge the PR as it is now?

2021-01-19 21:37 UTC, denhaandrei commented
> Have you tested it? Can I merge the PR as it is now?

Yes, please merge. Can you prepare new package?

2021-01-19 21:43 UTC, merged

2021-01-19 21:44 UTC, ghiscoding commented
by the end of this week probably